version: '3.8'

services:
  erp:
    restart: always
    build:
      context: .
      target: production
    environment:
      GO_APP_ENV: production
      DB_NAME: iota_erp
      DB_HOST: erp_db
      DB_PORT: 5432
      DB_PASSWORD: 2dP9L9d6gB9597
      DOMAIN: apollos.studio
      SESSION_DURATION: 720h
      INITIAL_USER_EMAIL: diyor_khaydarov@apollos.studio
      INITIAL_USER_PASSWORD: gSgnIInjB430
      MEILI_URL: http://meilisearch:7700
      MEILI_API_KEY: ${MEILI_MASTER_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.erp.rule=Host(`erp.iota.uz`)"
      - "traefik.http.routers.erp.tls=true"
      - "traefik.http.routers.erp.tls.certresolver=letsencrypt"
      - "traefik.http.services.erp.loadbalancer.server.port=3200"
    networks:
      - app

  erp_db:
    image: postgres:15.1
    restart: always
    hostname: erp_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2dP9L9d6gB9597
      POSTGRES_DB: iota_erp
    volumes:
      - ~/volumes/erp/postgres/data:/var/lib/postgresql/data
    networks:
      - app

  meilisearch:
    image: getmeili/meilisearch:v1.12
    restart: always
    hostname: meilisearch
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      MEILI_ENV: production
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - ~/volumes/erp/meilisearch/data:/meili_data
    networks:
      - app

networks:
  app:
    name: app
    external: true
